# Generated by Django 5.2.13 on 2026-04-17 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mythical_mane", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_notes",
                        to="mythical_mane.patient",
                    ),
                ),
            ],
            options={
                "db_table": "care_note",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
    ]
